export const LOGIN = "LOGIN";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_COMPLETE = "LOGOUT_COMPLETE";

export const TOGGLE_SESSION_MODAL = "TOGGLE_SESSION_MODAL";

export const GET_SESSION_TEMPLATES = "GET_SESSION_TEMPLATES";
export const GET_SESSIONS = "GET_SESIONS";
export const SESSION_TEMPLATES_RECEIVED = "SESSION_TEMPLATES_RECEIVED";
