export const LOGIN = "LOGIN";
export const LOGIN_COMPLETE = "LOGIN_COMPLETE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_COMPLETE = "LOGOUT_COMPLETE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_COMPLETE = "GET_USER_PROFILE_COMPLETE";

export const UPDATE_PAYMENT_STATUS = "UPDATE_PAYMENT_STATUS";
